App\Entity\Product:
    attributes:
        id:
            groups:
                - 'products-admin'
                - 'products-list'
        productName:
            groups:
                - 'products-admin'
                - 'products-list'
                - products-show
        sku:
            groups:
                - 'products-admin'
                - 'products-list'
                - products-show
        description:
            groups:
                - 'products-admin'
                - products-show
        createdAt:
            groups:
                - 'products-admin'
                - 'products-list'
                - products-show
        updatedAt:
            groups:
                - 'products-admin'
                - 'products-list'
                - products-show
        deleted:
            groups:
                - 'products-admin'
        deletedAt:
            groups:
                - 'products-admin'